# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20160929_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
