# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20160929_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='roomType',
            field=models.CharField(choices=[('2-Room Flexi', '2-Room Flexi'), ('3-Room', '3-Room'), ('4-Room', '4-Room'), ('5-Room', '5-Room'), ('3Gen', '3Gen'), ('Executive Flat', 'Executive Flat')], default='2-Room Flexi', max_length=15),
        ),
    ]
