# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-10 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_auto_20160905_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
